file_format: "0.3"

otpl:
    host: http://otel-collector-opentelemetry-collector.monitoring.svc

resource:
  attributes:
    - name: service.name
      value: ${SERVICE_NAME}
    - name: deployment.namespace
      value: ${POD_NAMESPACE}

tracer_provider:
  processors:
    - batch:
        exporter:
          otlp:
            protocol: grpc
            endpoint: ${otpl.host}:4317
  sampler:
    parent_based:
      root:
        trace_id_ratio_based:
          ratio: 0.1

meter_provider:
  readers:
    - periodic:
        interval: 15000
        exporter:
          otlp:
            protocol: grpc
            endpoint: ${otpl.host}

logger_provider:
  processors:
    - batch:
        exporter:
          otlp:
            protocol: grpc
            endpoint: ${otpl.host}